### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by spy14414** [rp5-tumcreate/basler-rgbd-driver#1]
Hi,I want to use your code for my tof camera and  pylon camera. Can you help me? When I built your code,I see this:
Errors     << basler_bridge:cmake /home/spy/basler-ros/logs/basler_bridge/build.cmake.002.log                                                 
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
CMake Error at /home/spy/basler-ros/src/basler_bridge/CMakeLists.txt:25 (find_package):
  By not providing "FindBasler.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Basler", but
  CMake did not find one.

  Could not find a package configuration file provided by "Basler" with any
  of the following names:

    BaslerConfig.cmake
    basler-config.cmake

  Add the installation prefix of "Basler" to CMAKE_PREFIX_PATH or set
  "Basler_DIR" to a directory containing one of the above files.  If "Basler"
  provides a separate development package or SDK, be sure it has been
  installed.

Thanks in advance.

**Comment by soulslicer** [comment]
https://github.com/rp5-tumcreate/basler-rgbd-driver/blob/master/cmake/modules/FindBasler.cmake

Just change these variables to where you stored your basler driver

**Comment by spy14414** [comment]
Thank you. I will try it again.

**Comment by spy14414** [comment]
Hi,I was faced the same question. I've already installed Basler tof and pylon5. (opt/BaslerToF opt/pylon5) I am not good at C++ and ROS(also English).
Maybe there's something wrong with the way I compile it.  
I did it in the following steps：
1. cd catkin_ws/src
2. git clone https://github.com/rp5-tumcreate/basler-rgbd-driver.git
3. cd catkin_ws
4.catkin build (or catkin_make) 
Is there any mistake? 

Thanks in advance.


> https://github.com/rp5-tumcreate/basler-rgbd-driver/blob/master/cmake/modules/FindBasler.cmake
> 
> Just change these variables to where you stored your basler driver

**Comment by soulslicer** [comment]
sorry you need to be familiar with C++ and ROS

Yes those steps are correct, after you have changed the FindBasler.cmake locations

**Comment by spy14414** [comment]
I'm sorry to bother you again.The code has been compiled by me.
I use:
basler-tof-driver-1.4.1.1450-x86_64
pylon_5.0.12.11829-deb0_amd64
opencv-3.4.3
ubuntu 16.04( virtual machine in VM ware）
 ros kinetic

Two cameras can run together.
I have copied the files in the /basler_bridge/data directory.
But there are still something wrong, LIke:

... logging to /home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/roslaunch-spy-4955.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://spy:40371/

SUMMARY
========

PARAMETERS
 * /RGB0_basler_rgb_bridge/basler_name: RGB0
 * /RGB0_basler_rgb_bridge/queue_size: 3
 * /RGB0_basler_rgb_bridge/serial_number: 21912212
 * /RGB0_basler_rgb_bridge/trigger: False
 * /RGB0_cloud_generator/pub_cloud_topic: RGB0/registered/p...
 * /RGB0_cloud_generator/pub_edge_topic: RGB0/edge_rect
 * /RGB0_cloud_generator/queue_size: 3
 * /RGB0_cloud_generator/republish: True
 * /RGB0_cloud_generator/sub_depth_info_topic: RGB0/registered/c...
 * /RGB0_cloud_generator/sub_depth_topic: RGB0/registered/d...
 * /RGB0_cloud_generator/sub_rgb_info_topic: RGB0/camera_info
 * /RGB0_cloud_generator/sub_rgb_topic: RGB0/image_color_...
 * /RGB0_cloud_generator/temporal_error: 0.1
 * /RGB0_cloud_generator/temporal_filter: True
 * /RGB0_cloud_generator/tf_target: RGB0_rgb_optical_...
 * /RGB0_cloud_generator/unorganize: True
 * /RGB0_compressed_publisher/compressed_topic_output: RGB0/image_color_...
 * /RGB0_compressed_publisher/queue_size: 3
 * /RGB0_compressed_publisher/raw_topic_input: RGB0/image_color_...
 * /RGB0_compressed_publisher/retime: False
 * /RGB0_compressed_subscriber/compressed_topic_input: RGB0/image_color_...
 * /RGB0_compressed_subscriber/queue_size: 3
 * /RGB0_compressed_subscriber/raw_topic_output: RGB0/image_color_...
 * /RGB0_compressed_subscriber/retime: False
 * /TOF0_basler_tof_bridge/basler_name: TOF0
 * /TOF0_basler_tof_bridge/queue_size: 3
 * /TOF0_basler_tof_bridge/serial_number: 23000299
 * /TOF0_basler_tof_bridge/trigger: False
 * /TOF0_depth_registration/calibration_mode: False
 * /TOF0_depth_registration/camera_name_from: TOF0
 * /TOF0_depth_registration/camera_name_to: RGB0
 * /TOF0_depth_registration/camera_serial_from: 23000299
 * /TOF0_depth_registration/camera_serial_to: 21912212
 * /TOF0_depth_registration/queue_size: 3
 * /TOF0_depth_registration/registered_resolution: [640, 480]
 * /basler_bridge/num_worker_threads: 8
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    RGB0_basler_rgb_bridge (nodelet/nodelet)
    RGB0_cloud_generator (nodelet/nodelet)
    RGB0_compressed_publisher (nodelet/nodelet)
    RGB0_compressed_subscriber (nodelet/nodelet)
    TOF0_basler_tof_bridge (nodelet/nodelet)
    TOF0_depth_registration (nodelet/nodelet)
    basler_bridge (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [5120]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e3a0a9b0-d8ee-11e9-931a-000c296c758d
process[rosout-1]: started with pid [5133]
started core service [/rosout]
process[basler_bridge-2]: started with pid [5136]
process[TOF0_basler_tof_bridge-3]: started with pid [5137]
process[RGB0_basler_rgb_bridge-4]: started with pid [5138]
process[RGB0_compressed_publisher-5]: started with pid [5139]
process[TOF0_depth_registration-6]: started with pid [5155]
process[RGB0_compressed_subscriber-7]: started with pid [5214]
process[RGB0_cloud_generator-8]: started with pid [5240]
[ INFO] [1568685634.369719200]: Initializing nodelet with 8 worker threads.
can't open pose file: /home/spy/basler-ros/src/basler_bridge/data/21912212/calib_pose.yaml
can't open depth file: /home/spy/basler-ros/src/basler_bridge/data/21912212/calib_depth.yaml
Camera Found
[ INFO] [1568685644.065019435]: drCallback
terminate called after throwing an instance of 'GenICam_3_0_Basler_pylon_v5_0::RuntimeException'
[FATAL] [1568685647.972486707]: Failed to load nodelet '/RGB0_cloud_generator` of type `cloud_generator/cloud_generator` to manager `basler_bridge'
[FATAL] [1568685647.973931942]: Failed to load nodelet '/RGB0_compressed_publisher` of type `od_compressed_image_transport/compressed_publisher` to manager `basler_bridge'
[FATAL] [1568685647.974406420]: Failed to load nodelet '/TOF0_basler_tof_bridge` of type `basler_bridge/basler_tof_bridge` to manager `basler_bridge'
[FATAL] [1568685647.974877777]: Failed to load nodelet '/RGB0_compressed_subscriber` of type `od_compressed_image_transport/compressed_subscriber` to manager `basler_bridge'
[basler_bridge-2] process has died [pid 5136, exit code -6, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=basler_bridge __log:=/home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/basler_bridge-2.log].
log file: /home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/basler_bridge-2*.log
[TOF0_basler_tof_bridge-3] process has died [pid 5137, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load basler_bridge/basler_tof_bridge basler_bridge __name:=TOF0_basler_tof_bridge __log:=/home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/TOF0_basler_tof_bridge-3.log].
log file: /home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/TOF0_basler_tof_bridge-3*.log
[RGB0_compressed_publisher-5] process has died [pid 5139, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load od_compressed_image_transport/compressed_publisher basler_bridge __name:=RGB0_compressed_publisher __log:=/home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/RGB0_compressed_publisher-5.log].
log file: /home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/RGB0_compressed_publisher-5*.log
[TOF0_depth_registration-6] process has finished cleanly
log file: /home/spy/.ros/log/e3a0a9b0-d8ee-11e9-931a-000c296c758d/TOF0_depth_registration-6*.log

Could you help me?
Thanks in  advance.
